{% set name = "niacin" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/niacin-{{ version }}.tar.gz
  sha256: e2b8a714330c699fa384c8d2d8b1e3d502515d9be9d6c5a318d26426191b997a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - nltk >=3.0
    - python >={{ python_min }}
    - regex
    - scipy >=1.0.0

test:
  imports:
    - niacin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/niacin/
  summary: A Python library for replacing the missing variation in your text data
  description: |
    Data collected for model training necessarily undersamples the likely variance in the input space. This library is a collection of tools for inserting typical kinds of perturbations to better approximate population variance; and, for creating similar-but-incorrect examples to aid in reducing the total size of the hypothesis space.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://niacin.readthedocs.io
  dev_url: https://github.com/deniederhut/niacin

extra:
  recipe-maintainers:
    - deniederhut
